export const US_CITIES = [
  'New York, NY', 'Los Angeles, CA', 'Chicago, IL', 'Houston, TX', 'Phoenix, AZ',
  'Philadelphia, PA', 'San Antonio, TX', 'San Diego, CA', 'Dallas, TX', 'Austin, TX',
  'Jacksonville, FL', 'Fort Worth, TX', 'San Jose, CA', 'Columbus, OH', 'Charlotte, NC',
  'Indianapolis, IN', 'San Francisco, CA', 'Seattle, WA', 'Denver, CO', 'Oklahoma City, OK',
  'Nashville, TN', 'Washington, DC', 'El Paso, TX', 'Las Vegas, NV', 'Boston, MA',
  'Detroit, MI', 'Portland, OR', 'Louisville, KY', 'Memphis, TN', 'Baltimore, MD',
  'Milwaukee, WI', 'Albuquerque, NM', 'Tucson, AZ', 'Fresno, CA', 'Sacramento, CA',
  'Mesa, AZ', 'Kansas City, MO', 'Atlanta, GA', 'Omaha, NE', 'Colorado Springs, CO',
  'Raleigh, NC', 'Miami, FL', 'Long Beach, CA', 'Virginia Beach, VA', 'Oakland, CA',
  'Minneapolis, MN', 'Tulsa, OK', 'Tampa, FL', 'Arlington, TX', 'New Orleans, LA',
  'Wichita, KS', 'Cleveland, OH', 'Bakersfield, CA', 'Aurora, CO', 'Anaheim, CA',
  'Honolulu, HI', 'Santa Ana, CA', 'Riverside, CA', 'Corpus Christi, TX', 'Lexington, KY',
  'Stockton, CA', 'Henderson, NV', 'Saint Paul, MN', 'St. Louis, MO', 'Cincinnati, OH',
  'Pittsburgh, PA', 'Greensboro, NC', 'Anchorage, AK', 'Plano, TX', 'Lincoln, NE',
  'Orlando, FL', 'Irvine, CA', 'Newark, NJ', 'Toledo, OH', 'Durham, NC',
  'Chula Vista, CA', 'Fort Wayne, IN', 'Jersey City, NJ', 'St. Petersburg, FL', 'Laredo, TX',
  'Madison, WI', 'Chandler, AZ', 'Buffalo, NY', 'Lubbock, TX', 'Scottsdale, AZ',
  'Reno, NV', 'Glendale, AZ', 'Gilbert, AZ', 'Winston-Salem, NC', 'North Las Vegas, NV',
  'Norfolk, VA', 'Chesapeake, VA', 'Garland, TX', 'Irving, TX', 'Hialeah, FL',
  'Fremont, CA', 'Boise, ID', 'Richmond, VA', 'Baton Rouge, LA', 'Spokane, WA',
];